#!/usr/bin/env bash
# scripts/memoryx_runtime_lockdown.sh
#
# MemoryX 2.0.0 stable runtime + guardrails setup.
#
# Safe by design:
# - does NOT move or create release tags
# - does NOT publish GitHub releases
# - does NOT edit runtime DB contents
# - does NOT modify MemoryX core logic
# - only creates operational guard/config files and a stable runtime checkout
#
# Usage:
#   chmod +x scripts/memoryx_runtime_lockdown.sh
#   ./scripts/memoryx_runtime_lockdown.sh all
#
# Optional:
#   MEMORYX_REPO_URL=https://github.com/luckyl214/memoryx.git ./scripts/memoryx_runtime_lockdown.sh all
#   MEMORYX_RUNTIME_ROOT="$HOME/runtime" ./scripts/memoryx_runtime_lockdown.sh setup-runtime
#   MEMORYX_EXPECTED_VERSION=2.0.0 ./scripts/memoryx_runtime_lockdown.sh smoke

set -Eeuo pipefail

MEMORYX_REPO_URL="${MEMORYX_REPO_URL:-https://github.com/luckyl214/memoryx.git}"
MEMORYX_STABLE_TAG="${MEMORYX_STABLE_TAG:-v2.0.0}"
MEMORYX_EXPECTED_VERSION="${MEMORYX_EXPECTED_VERSION:-2.0.0}"

MEMORYX_RUNTIME_ROOT="${MEMORYX_RUNTIME_ROOT:-$HOME/runtime}"
MEMORYX_RUNTIME_DIR="${MEMORYX_RUNTIME_DIR:-$MEMORYX_RUNTIME_ROOT/memoryx-$MEMORYX_EXPECTED_VERSION}"
MEMORYX_HOME="${MEMORYX_HOME:-$HOME/.memoryx}"
MEMORYX_ENV_FILE="${MEMORYX_ENV_FILE:-$MEMORYX_HOME/memoryx.env}"
HERMES_CONFIG_DIR="${HERMES_CONFIG_DIR:-$HOME/.config/hermes}"
HERMES_MEMORYX_ENV_FILE="${HERMES_MEMORYX_ENV_FILE:-$HERMES_CONFIG_DIR/memoryx.env}"

PYTHON_BIN="${PYTHON_BIN:-python3.12}"

SCRIPT_NAME="$(basename "$0")"

log() {
  printf '\n[%s] %s\n' "$SCRIPT_NAME" "$*"
}

die() {
  printf '\n[%s] ERROR: %s\n' "$SCRIPT_NAME" "$*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

repo_root_or_die() {
  git rev-parse --show-toplevel >/dev/null 2>&1 || die "Run this script inside the MemoryX git repository."
  git rev-parse --show-toplevel
}

assert_not_dirty_for_repo_guardrails() {
  local root
  root="$(repo_root_or_die)"
  cd "$root"

  if [[ -n "$(git status --short)" ]]; then
    cat >&2 <<EOF

[$SCRIPT_NAME] Worktree is not clean.

This script refuses to install repository guardrails into a dirty tree because
we do not want to mix guardrail files with unrelated edits.

Run:
  git status --short

Then either commit/stash your current changes or run:
  ./scripts/memoryx_runtime_lockdown.sh setup-runtime
  ./scripts/memoryx_runtime_lockdown.sh setup-hermes-config

EOF
    exit 1
  fi
}

assert_stable_tag_remote() {
  need_cmd git

  log "Checking remote stable tag exists: $MEMORYX_STABLE_TAG"
  git ls-remote --tags "$MEMORYX_REPO_URL" "$MEMORYX_STABLE_TAG" | grep -q "$MEMORYX_STABLE_TAG" \
    || die "Remote tag not found: $MEMORYX_STABLE_TAG at $MEMORYX_REPO_URL"
}

setup_runtime_dirs() {
  log "Creating runtime directories under $MEMORYX_HOME"

  mkdir -p "$MEMORYX_HOME/data"
  mkdir -p "$MEMORYX_HOME/traces"
  mkdir -p "$MEMORYX_HOME/logs"
  mkdir -p "$MEMORYX_HOME/vector"
  mkdir -p "$MEMORYX_HOME/backups"
  mkdir -p "$MEMORYX_HOME/bin"
  mkdir -p "$HERMES_CONFIG_DIR"

  chmod 700 "$MEMORYX_HOME"
  chmod 700 "$MEMORYX_HOME/data" "$MEMORYX_HOME/traces" "$MEMORYX_HOME/logs" "$MEMORYX_HOME/vector" "$MEMORYX_HOME/backups"
}

write_memoryx_env() {
  log "Writing MemoryX env file: $MEMORYX_ENV_FILE"

  cat > "$MEMORYX_ENV_FILE" <<EOF
# MemoryX stable runtime environment.
# Generated by scripts/memoryx_runtime_lockdown.sh.
# Do not commit this file to Git.

export MEMORYX_HOME="$MEMORYX_HOME"
export MEMORYX_DB_PATH="\$MEMORYX_HOME/data/memoryx.db"
export MEMORYX_TRACE_PATH="\$MEMORYX_HOME/traces/guard_trace.jsonl"
export MEMORYX_VECTOR_PATH="\$MEMORYX_HOME/vector"
export MEMORYX_LOG_LEVEL="INFO"

# API auth:
# Leave empty to disable API auth.
# Set a real key to enable auth.
# export MEMORYX_API_KEY=""

# Stable version expected by Hermes:
export MEMORYX_EXPECTED_VERSION="$MEMORYX_EXPECTED_VERSION"

# Stable runtime checkout:
export MEMORYX_RUNTIME_DIR="$MEMORYX_RUNTIME_DIR"
EOF

  chmod 600 "$MEMORYX_ENV_FILE"

  cp "$MEMORYX_ENV_FILE" "$HERMES_MEMORYX_ENV_FILE"
  chmod 600 "$HERMES_MEMORYX_ENV_FILE"

  log "Hermes MemoryX env copied to: $HERMES_MEMORYX_ENV_FILE"
}

clone_or_update_runtime_checkout() {
  need_cmd git
  assert_stable_tag_remote

  mkdir -p "$MEMORYX_RUNTIME_ROOT"

  if [[ -d "$MEMORYX_RUNTIME_DIR/.git" ]]; then
    log "Existing runtime checkout found: $MEMORYX_RUNTIME_DIR"
    cd "$MEMORYX_RUNTIME_DIR"

    if [[ -n "$(git status --short)" ]]; then
      die "Runtime checkout is dirty. Refusing to proceed: $MEMORYX_RUNTIME_DIR"
    fi

    git fetch --tags origin
    git checkout "$MEMORYX_STABLE_TAG"
  else
    log "Cloning MemoryX stable runtime to: $MEMORYX_RUNTIME_DIR"
    git clone "$MEMORYX_REPO_URL" "$MEMORYX_RUNTIME_DIR"
    cd "$MEMORYX_RUNTIME_DIR"
    git fetch --tags origin
    git checkout "$MEMORYX_STABLE_TAG"
  fi

  local tag_type
  tag_type="$(git cat-file -t "$MEMORYX_STABLE_TAG" || true)"
  [[ "$tag_type" == "tag" ]] || die "$MEMORYX_STABLE_TAG is not an annotated tag. got: $tag_type"

  local commit
  commit="$(git rev-list -n 1 "$MEMORYX_STABLE_TAG" --abbrev-commit)"
  log "Runtime checkout pinned: $MEMORYX_STABLE_TAG -> $commit"
}

create_runtime_venv_and_install() {
  need_cmd "$PYTHON_BIN"

  cd "$MEMORYX_RUNTIME_DIR"

  log "Creating runtime venv with $PYTHON_BIN"
  "$PYTHON_BIN" -m venv .venv

  # shellcheck disable=SC1091
  . .venv/bin/activate

  python -m pip install --upgrade pip -q

  log "Installing MemoryX stable package"
  python -m pip install -q .

  log "Installing dev extras for smoke/test utilities if available"
  python -m pip install -q ".[dev]" || {
    log "WARNING: .[dev] install failed or unavailable. Core package install already succeeded."
  }

  log "Installed package version:"
  python - <<PY
import memoryx
print("memoryx.__version__ =", getattr(memoryx, "__version__", "UNKNOWN"))
assert getattr(memoryx, "__version__", None) == "$MEMORYX_EXPECTED_VERSION"
PY
}

write_runtime_smoke_script() {
  local smoke="$MEMORYX_HOME/bin/memoryx_runtime_smoke.sh"

  log "Writing runtime smoke script: $smoke"

  cat > "$smoke" <<'SMOKEEOF'
#!/usr/bin/env bash
set -Eeuo pipefail

: "${MEMORYX_HOME:=$HOME/.memoryx}"
: "${MEMORYX_DB_PATH:=$MEMORYX_HOME/data/memoryx.db}"
: "${MEMORYX_EXPECTED_VERSION:=2.0.0}"
: "${MEMORYX_RUNTIME_DIR:=$HOME/runtime/memoryx-2.0.0}"

source "$MEMORYX_RUNTIME_DIR/.venv/bin/activate"

python - <<PY
from pathlib import Path
from os import environ
import memoryx

expected = environ.get("MEMORYX_EXPECTED_VERSION", "2.0.0")
actual = getattr(memoryx, "__version__", None)
assert actual == expected, f"MemoryX version mismatch: expected={expected}, actual={actual}"
print("version smoke: PASS -", actual)

db_path = Path(environ["MEMORYX_DB_PATH"])
db_path.parent.mkdir(parents=True, exist_ok=True)

from memoryx.storage.repository import MemoryRepository
repo = MemoryRepository(db_path=db_path)
mid = repo.store_memory(
    content="MemoryX stable runtime smoke",
    session_id="runtime-smoke",
    memory_type="FACT",
    scope="session",
)
assert mid
print("repository smoke: PASS -", mid)
PY
SMOKEEOF

  chmod +x "$smoke"
}

write_hermes_preflight() {
  local py="$MEMORYX_HOME/bin/hermes_memoryx_preflight.py"
  local sh="$MEMORYX_HOME/bin/hermes_memoryx_preflight.sh"

  log "Writing Hermes MemoryX preflight: $py"

  cat > "$py" <<'PYEOF'
#!/usr/bin/env python3
"""
Hermes -> MemoryX preflight.

Purpose:
- fail fast if Hermes is not using the stable MemoryX runtime
- prevent accidental use of dev checkout or wrong version
- verify runtime DB path is outside the git repository
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


EXPECTED = os.environ.get("MEMORYX_EXPECTED_VERSION", "2.0.0")


def fail(msg: str) -> None:
    print(f"[hermes_memoryx_preflight] FAIL: {msg}", file=sys.stderr)
    raise SystemExit(1)


def ok(msg: str) -> None:
    print(f"[hermes_memoryx_preflight] PASS: {msg}")


def main() -> None:
    try:
        import memoryx
    except Exception as exc:
        fail(f"cannot import memoryx: {exc!r}")

    actual = getattr(memoryx, "__version__", None)
    if actual != EXPECTED:
        fail(f"memoryx version mismatch: expected={EXPECTED!r}, actual={actual!r}")

    module_file = Path(getattr(memoryx, "__file__", "")).resolve()
    ok(f"memoryx version {actual}")
    ok(f"memoryx module {module_file}")

    db_path = Path(os.environ.get("MEMORYX_DB_PATH", "")).expanduser()
    if not db_path:
        fail("MEMORYX_DB_PATH is not set")

    db_path = db_path.resolve()
    home = Path(os.environ.get("MEMORYX_HOME", str(Path.home() / ".memoryx"))).expanduser().resolve()

    if home not in [db_path, *db_path.parents]:
        fail(f"MEMORYX_DB_PATH must be under MEMORYX_HOME. db={db_path}, home={home}")

    if ".git" in db_path.parts:
        fail(f"MEMORYX_DB_PATH must not be inside a git repo: {db_path}")

    if db_path.name in {"memoryx.db", "memoryx.sqlite", "memoryx_public_smoke.db"}:
        ok(f"runtime db path {db_path}")
    else:
        ok(f"runtime db path {db_path}")

    # Repository import smoke.
    try:
        from memoryx.storage.repository import MemoryRepository
    except Exception as exc:
        fail(f"cannot import MemoryRepository: {exc!r}")

    ok("MemoryRepository import")

    print("[hermes_memoryx_preflight] ALL PASS")


if __name__ == "__main__":
    main()
PYEOF

  chmod +x "$py"

  cat > "$sh" <<SHEOF
#!/usr/bin/env bash
set -Eeuo pipefail

source "$MEMORYX_ENV_FILE"
source "$MEMORYX_RUNTIME_DIR/.venv/bin/activate"
python "$py"
SHEOF

  chmod +x "$sh"

  log "Hermes preflight shell wrapper: $sh"
}

make_runtime_readonly() {
  log "Making runtime checkout read-only: $MEMORYX_RUNTIME_DIR"
  chmod -R a-w "$MEMORYX_RUNTIME_DIR"
  log "Runtime source is now read-only. Runtime data remains writable under $MEMORYX_HOME"
}

setup_runtime() {
  setup_runtime_dirs
  write_memoryx_env
  clone_or_update_runtime_checkout
  create_runtime_venv_and_install
  write_runtime_smoke_script
  write_hermes_preflight
  make_runtime_readonly

  log "Runtime setup complete."
  log "Load env with: source $MEMORYX_ENV_FILE"
  log "Run smoke: $MEMORYX_HOME/bin/memoryx_runtime_smoke.sh"
  log "Run Hermes preflight: $MEMORYX_HOME/bin/hermes_memoryx_preflight.sh"
}

write_agent_rules() {
  local root="$1"

  cat > "$root/AGENT_RULES.md" <<'EOF'
# MemoryX Agent Rules

MemoryX v2.0.0 stable is frozen.

## Absolute prohibitions

Agents must not:

- move, delete, recreate, or overwrite these tags:
  - v2.0.0
  - v2.0.0-rc.1
  - v2.0.0-rc.2
- edit GitHub release assets
- edit runtime data:
  - .env
  - runtime DB
  - logs
  - traces
  - vector stores
  - lancedb runtime directories
- disable SQLite foreign keys
- use INSERT OR IGNORE to hide parent-row / FK errors
- make schema or migration changes without explicit batch approval
- use pytest skip/xfail to clear release failures
- run git add .
- tag from a dirty worktree
- publish from a dirty worktree
- mix docs/hygiene changes with core logic fixes
- treat Hermes update failures as MemoryX failures without attribution

## Required workflow before any commit

1. Identify batch:
   - hotfix
   - patch
   - docs
   - hygiene
   - feature
2. Define allowed files.
3. Define forbidden files.
4. Run:
   - git status --short
   - python -m pytest --collect-only -q
   - python -m pytest -q
   - python scripts/run_memoryx_release_gate.py
5. If packaging changed, run archive hygiene.
6. Commit only explicit files.

## Stable release rule

v2.0.0 is immutable. Any fix must become:

- v2.0.1 for patch/hotfix
- v2.1.0-rc.1 for feature/minor work
EOF
}

write_codeowners() {
  local root="$1"
  mkdir -p "$root/.github"

  cat > "$root/.github/CODEOWNERS" <<'EOF'
# MemoryX CODEOWNERS
# Enable "Require review from Code Owners" in GitHub branch protection.

* @luckyl214

memoryx/storage/ @luckyl214
memoryx/guards/ @luckyl214
memoryx/hooks/ @luckyl214
memoryx/hermes_bridge.py @luckyl214
memoryx/plugin.py @luckyl214
memoryx/api/ @luckyl214
memoryx/mcp_server.py @luckyl214

db/schema.sql @luckyl214
db/migrations/ @luckyl214

pyproject.toml @luckyl214
VERSION @luckyl214
scripts/run_memoryx_release_gate.py @luckyl214
scripts/ @luckyl214
.github/ @luckyl214
EOF
}

write_pr_template() {
  local root="$1"
  mkdir -p "$root/.github"

  cat > "$root/.github/pull_request_template.md" <<'EOF'
## MemoryX Change Gate

### Batch

- [ ] hotfix
- [ ] patch
- [ ] docs-only
- [ ] hygiene-only
- [ ] feature / minor
- [ ] other:

### Problem

Describe the exact failure or need.

### Root cause

Describe the verified root cause. Do not guess.

### Scope

Allowed files:

-

Forbidden files:

-

### Change summary

-

### Tests

Paste exact results:

```text
python -m pytest --collect-only -q
python -m pytest -q
python scripts/run_memoryx_release_gate.py
```

### Archive hygiene

Required if packaging/release/docs/runtime paths changed.

```text
archive hygiene:
secret scan:
private path scan:
```

### Risk

*

### Rollback

*

### Release impact

* [ ] no release needed
* [ ] patch v2.0.x candidate
* [ ] minor v2.1.0-rc.1 candidate
EOF
}

write_constraints() {
  local root="$1"

  cat > "$root/constraints-memoryx-stable.txt" <<'EOF'
# Keep Hermes pinned to MemoryX stable unless explicitly testing a patch.
# Use:
#   pip install -r requirements-hermes.txt -c constraints-memoryx-stable.txt
#
# Do not change this to a branch name or local path.

memoryx @ git+https://github.com/luckyl214/memoryx.git@v2.0.0
EOF
}

write_repo_guard_script() {
  local root="$1"
  mkdir -p "$root/scripts"

  cat > "$root/scripts/memoryx_repo_guard.py" <<'PYEOF'
#!/usr/bin/env python3
"""
MemoryX repository guard.

Run before committing or asking an agent to modify the repo.

Checks:
- worktree status visibility
- forbidden runtime/private files
- protected tags not moved locally
- package version consistency
- stable tag hygiene hints

This script intentionally does not mutate repository state.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

PROTECTED_TAGS = ["v2.0.0", "v2.0.0-rc.1", "v2.0.0-rc.2"]
FORBIDDEN_PATH_PATTERNS = [
    re.compile(r"(^|/)\.env($|/)"),
    re.compile(r"(^|/)reports($|/)"),
    re.compile(r"(^|/)artifacts($|/)"),
    re.compile(r"(^|/)logs($|/)"),
    re.compile(r"(^|/)traces($|/)"),
    re.compile(r"(^|/)lancedb($|/)"),
    re.compile(r"\.sqlite$"),
    re.compile(r"\.db$"),
    re.compile(r"__pycache__"),
    re.compile(r"\.pytest_cache"),
]
SECRET_PATTERNS = [
    re.compile(r"OPENAI_API_KEY\s*="),
    re.compile(r"SILICONFLOW_API_KEY\s*="),
    re.compile(r"api[_-]?key\s*=\s*['\"][A-Za-z0-9_\-]{16,}", re.I),
    re.compile(r"secret\s*=\s*['\"][A-Za-z0-9_\-]{16,}", re.I),
    re.compile(r"token\s*=\s*['\"][A-Za-z0-9_\-]{16,}", re.I),
    re.compile(r"password\s*=\s*['\"][^'\"]{8,}", re.I),
]


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def fail(msg: str) -> None:
    print(f"[memoryx_repo_guard] FAIL: {msg}", file=sys.stderr)
    raise SystemExit(1)


def warn(msg: str) -> None:
    print(f"[memoryx_repo_guard] WARN: {msg}")


def ok(msg: str) -> None:
    print(f"[memoryx_repo_guard] PASS: {msg}")


def repo_root() -> Path:
    try:
        cp = run(["git", "rev-parse", "--show-toplevel"])
    except Exception:
        fail("not inside a git repository")
    return Path(cp.stdout.strip())


def git_status(root: Path) -> list[str]:
    cp = run(["git", "status", "--short"], check=True)
    lines = [x for x in cp.stdout.splitlines() if x.strip()]
    if lines:
        warn("worktree is dirty:")
        for line in lines:
            print(f"  {line}")
    else:
        ok("worktree clean")
    return lines


def check_forbidden_paths(root: Path) -> None:
    cp = run(["git", "ls-files"], check=True)
    bad: list[str] = []
    for rel in cp.stdout.splitlines():
        for pat in FORBIDDEN_PATH_PATTERNS:
            if pat.search(rel):
                bad.append(rel)
                break
    if bad:
        print("\nForbidden tracked paths:")
        for item in bad:
            print(f"  {item}")
        fail("forbidden runtime/private files are tracked")
    ok("no forbidden runtime/private tracked files")


def check_secret_patterns(root: Path) -> None:
    cp = run(["git", "ls-files"], check=True)
    bad: list[tuple[str, int, str]] = []

    skip_ext = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".pdf", ".gz", ".zip"}
    for rel in cp.stdout.splitlines():
        path = root / rel
        if path.suffix.lower() in skip_ext:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue

        for i, line in enumerate(text.splitlines(), 1):
            if "your_" in line or "placeholder" in line.lower() or "example" in rel.lower():
                continue
            for pat in SECRET_PATTERNS:
                if pat.search(line):
                    bad.append((rel, i, line.strip()))
                    break

    if bad:
        print("\nPossible secret hits:")
        for rel, line_no, line in bad[:50]:
            print(f"  {rel}:{line_no}: {line}")
        fail("possible secrets found")
    ok("secret pattern scan clean")


def check_tags() -> None:
    for tag in PROTECTED_TAGS:
        cp = run(["git", "tag", "-l", tag], check=True)
        if not cp.stdout.strip():
            warn(f"protected tag not present locally: {tag}")
            continue
        tag_type = run(["git", "cat-file", "-t", tag], check=False)
        if tag_type.returncode == 0 and tag_type.stdout.strip() != "tag":
            fail(f"{tag} is not an annotated tag locally; got {tag_type.stdout.strip()!r}")
        ok(f"protected tag present and annotated locally: {tag}")


def check_version(root: Path) -> None:
    pyproject = root / "pyproject.toml"
    init_py = root / "memoryx" / "__init__.py"
    version_file = root / "VERSION"

    expected = "2.0.0"
    text = pyproject.read_text(encoding="utf-8")
    if 'version = "2.0.0"' not in text:
        warn('pyproject.toml does not contain version = "2.0.0"')

    if init_py.exists():
        init_text = init_py.read_text(encoding="utf-8")
        if '__version__ = "2.0.0"' not in init_text and "__version__='2.0.0'" not in init_text:
            warn("memoryx/__init__.py may not expose __version__ = 2.0.0")

    if version_file.exists() and version_file.read_text(encoding="utf-8").strip() != expected:
        warn("VERSION file is not 2.0.0")

    ok("version metadata checked")


def main() -> None:
    root = repo_root()
    os.chdir(root)
    print(f"[memoryx_repo_guard] repo: {root}")

    git_status(root)
    check_forbidden_paths(root)
    check_secret_patterns(root)
    check_tags()
    check_version(root)

    print("[memoryx_repo_guard] DONE")


if __name__ == "__main__":
    main()
PYEOF

  chmod +x "$root/scripts/memoryx_repo_guard.py"
}

write_github_actions_gate() {
  local root="$1"
  mkdir -p "$root/.github/workflows"

  cat > "$root/.github/workflows/memoryx-release-gate.yml" <<'EOF'
name: MemoryX ReleaseGate

on:
  pull_request:
  push:
    branches:
      - memoryx-2-kernel
      - main

jobs:
  release-gate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Collect tests
        run: |
          python -m pytest --collect-only -q

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Run MemoryX ReleaseGate
        run: |
          python scripts/run_memoryx_release_gate.py

      - name: Repository guard
        run: |
          python scripts/memoryx_repo_guard.py
EOF
}

print_github_manual_ruleset_instructions() {
  cat <<'EOF'

================================================================================
Manual GitHub protection setup required
=======================================

The script generated repo guardrails, but GitHub branch/tag protection requires
repo admin permissions.

Configure in GitHub UI:

Repository -> Settings -> Rules -> Rulesets

Ruleset 1: protect stable tags

* Target: tags
* Pattern: v*
* Block deletion: ON
* Block force push / update: ON
* Restrict who can create matching refs: owner only, if available

Ruleset 2: protect main branches

* Target branches:

  * main
  * memoryx-2-kernel
* Require pull request before merge: ON
* Require status checks: ON
* Require linear history: ON
* Block force pushes: ON
* Block deletions: ON
* Require CODEOWNERS review: ON

Required status check:

* MemoryX ReleaseGate / release-gate

# Do not mark this step complete until GitHub UI shows the rules are active.

EOF
}

install_repo_guardrails() {
  local root
  root="$(repo_root_or_die)"
  cd "$root"

  assert_not_dirty_for_repo_guardrails

  log "Installing repository guardrails into: $root"

  write_agent_rules "$root"
  write_codeowners "$root"
  write_pr_template "$root"
  write_constraints "$root"
  write_repo_guard_script "$root"
  write_github_actions_gate "$root"

  log "Repository guardrails written."
  python "$root/scripts/memoryx_repo_guard.py" || true

  print_github_manual_ruleset_instructions

  cat <<EOF

Next steps:
git status --short
git add AGENT_RULES.md .github/CODEOWNERS .github/pull_request_template.md .github/workflows/memoryx-release-gate.yml constraints-memoryx-stable.txt scripts/memoryx_repo_guard.py
git commit -m "chore: add MemoryX runtime and agent guardrails"
git push origin memoryx-2-kernel

Do NOT run git add .
EOF
}

setup_hermes_config() {
  setup_runtime_dirs
  write_memoryx_env
  write_hermes_preflight

  cat <<EOF

Hermes config ready.

To load before Hermes starts:
source "$HERMES_MEMORYX_ENV_FILE"
"$MEMORYX_HOME/bin/hermes_memoryx_preflight.sh"

Recommended Hermes startup guard:
call "$MEMORYX_HOME/bin/hermes_memoryx_preflight.sh" before enabling any MemoryX plugin hooks.
EOF
}

run_smoke() {
  source "$MEMORYX_ENV_FILE"
  "$MEMORYX_HOME/bin/memoryx_runtime_smoke.sh"
  "$MEMORYX_HOME/bin/hermes_memoryx_preflight.sh"
}

show_status() {
  cat <<EOF
MemoryX stable runtime status

MEMORYX_REPO_URL:          $MEMORYX_REPO_URL
MEMORYX_STABLE_TAG:        $MEMORYX_STABLE_TAG
MEMORYX_EXPECTED_VERSION:  $MEMORYX_EXPECTED_VERSION
MEMORYX_RUNTIME_DIR:       $MEMORYX_RUNTIME_DIR
MEMORYX_HOME:              $MEMORYX_HOME
MEMORYX_ENV_FILE:          $MEMORYX_ENV_FILE
HERMES_MEMORYX_ENV_FILE:   $HERMES_MEMORYX_ENV_FILE

Commands:
source "$MEMORYX_ENV_FILE"
"$MEMORYX_HOME/bin/memoryx_runtime_smoke.sh"
"$MEMORYX_HOME/bin/hermes_memoryx_preflight.sh"
EOF
}

usage() {
  cat <<EOF
Usage:
$0 all
$0 setup-runtime
$0 setup-hermes-config
$0 install-repo-guardrails
$0 smoke
$0 status

Recommended:
$0 all
EOF
}

main() {
  local cmd="${1:-}"
  local initial_dir
  initial_dir="$(repo_root_or_die)"

  case "$cmd" in
    all)
      setup_runtime
      cd "$initial_dir"
      install_repo_guardrails
      run_smoke
      show_status
      ;;
    setup-runtime)
      setup_runtime
      ;;
    setup-hermes-config)
      setup_hermes_config
      ;;
    install-repo-guardrails)
      install_repo_guardrails
      ;;
    smoke)
      run_smoke
      ;;
    status)
      show_status
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
