from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from typing import Any

from .knowledge_distillation import KnowledgeDistillationEngine
from .storage import MemoryRecord


class PersonaEngine:
    """
    Persona 画像合成引擎 — 参考 TencentDB L3 Persona 设计。

    定期扫描所有记忆，从稳定偏好、编码习惯、项目原则等维度
    合成人类可读 + LLM 可读的 Markdown 用户画像。
    """

    def __init__(self, *, repository, llm_summarize=None) -> None:
        self.repository = repository
        self.llm_summarize = llm_summarize
        self.distiller = KnowledgeDistillationEngine(repository=repository)

    async def generate(self, *, session_id: str | None = None, persist: bool = False) -> dict[str, Any]:
        """生成 Persona 画像。"""
        artifact = await self.distiller.distill(persist=False)

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        sections: list[str] = [
            f"# Persona · Generated {now}",
            "",
        ]

        if artifact.stable_preferences:
            sections.append("## Stable Preferences")
            for pref in artifact.stable_preferences[:8]:
                sections.append(f"- {pref}")
            sections.append("")

        if artifact.project_principles:
            sections.append("## Project Principles")
            for principle in artifact.project_principles[:5]:
                sections.append(f"- {principle}")
            sections.append("")

        if artifact.coding_habits:
            sections.append("## Coding Habits")
            for habit in artifact.coding_habits[:5]:
                sections.append(f"- {habit}")
            sections.append("")

        if artifact.long_term_profile:
            sections.append("## Profile Summary")
            for item in artifact.long_term_profile[:5]:
                sections.append(f"- {item}")
            sections.append("")

        if artifact.repetitive_patterns:
            sections.append("## Recurring Patterns")
            for pattern in artifact.repetitive_patterns[:5]:
                sections.append(f"- {pattern}")
            sections.append("")

        sections.append("---")
        sections.append("_Automatically generated by Mnemosyne-X PersonaEngine._")

        markdown = "\n".join(sections)

        result = {
            "markdown": markdown,
            "stable_preferences": artifact.stable_preferences,
            "project_principles": artifact.project_principles,
            "coding_habits": artifact.coding_habits,
            "profile_summary": artifact.long_term_profile,
            "recurring_patterns": artifact.repetitive_patterns,
            "source_count": artifact.source_count,
        }

        if persist:
            content_hash = hashlib.sha256(markdown.encode()).hexdigest()
            await self.repository.db.execute(
                "INSERT INTO reflection_summaries(id, summary, content_hash, checksum, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);",
                (__import__("uuid").uuid4().hex, markdown, content_hash, content_hash),
            )

        return result
