CREATE INDEX IF NOT EXISTS idx_memories_session_id ON memories(session_id);
CREATE INDEX IF NOT EXISTS idx_memories_active_state ON memories(active_state);
CREATE INDEX IF NOT EXISTS idx_memories_valid_from ON memories(valid_from);
CREATE INDEX IF NOT EXISTS idx_memories_valid_to ON memories(valid_to);
CREATE INDEX IF NOT EXISTS idx_memories_importance ON memories(importance_score DESC);
CREATE INDEX IF NOT EXISTS idx_memories_confidence ON memories(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_memories_access_count ON memories(access_count DESC);
CREATE INDEX IF NOT EXISTS idx_memories_reinforcement ON memories(reinforcement_score DESC);
CREATE INDEX IF NOT EXISTS idx_memories_safety ON memories(safety_score ASC);
CREATE INDEX IF NOT EXISTS idx_memory_versions_memory_id ON memory_versions(memory_id, version DESC);
CREATE INDEX IF NOT EXISTS idx_memory_conflicts_memory_id ON memory_conflicts(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_conflicts_conflicting_memory_id ON memory_conflicts(conflicting_memory_id);
CREATE INDEX IF NOT EXISTS idx_archived_memories_memory_id ON archived_memories(memory_id);
CREATE INDEX IF NOT EXISTS idx_episodic_memories_session_id ON episodic_memories(session_id);
CREATE INDEX IF NOT EXISTS idx_reflection_summaries_session_id ON reflection_summaries(session_id);
CREATE INDEX IF NOT EXISTS idx_session_summaries_session_id ON session_summaries(session_id);
CREATE INDEX IF NOT EXISTS idx_entities_name_type ON entities(normalized_name, entity_type);
CREATE INDEX IF NOT EXISTS idx_relations_source_target ON relations(source_entity_id, target_entity_id);
CREATE INDEX IF NOT EXISTS idx_memory_access_logs_memory_id ON memory_access_logs(memory_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reinforcement_events_memory_id ON reinforcement_events(memory_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_safety_quarantine_memory_id ON safety_quarantine(memory_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);
