"""溢出内容写入 markdown 文件并上传到飞书。

不在卡片里说"已转附件"除非真的上传成功了。
"""
from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Any


def safe_filename(text: str, fallback: str = "hermes_answer") -> str:
    """从文本中提取安全的文件名（中英文/数字/下划线/点/连字符）"""
    name = re.sub(r"[^\w\u4e00-\u9fff.-]+", "_", text.strip())[:60]
    return name or fallback


class OverflowFileWriter:
    """将溢出内容写入本地 markdown 文件。"""

    def __init__(self, spool_dir: str | Path) -> None:
        self.spool_dir = Path(spool_dir)
        self.spool_dir.mkdir(parents=True, exist_ok=True)

    def write_markdown(
        self,
        *,
        job_id: str,
        title: str,
        content: str,
    ) -> Path:
        """写入 markdown 文件，返回路径。"""
        ts = time.strftime("%Y%m%d-%H%M%S")
        filename = f"{ts}_{safe_filename(title)}_{job_id[:8]}.md"
        path = self.spool_dir / filename
        path.write_text(
            f"# {title}\n\n"
            f"> Generated by Hermes · MemoryX\n\n"
            f"{content.strip()}\n",
            encoding="utf-8",
        )
        return path
