"""溢出内容转 Markdown 文件 + 上传飞书云盘。

P14.4.1 UX Reliability Hotfix:
- 长答案超限时真正生成 .md 文件并上传
- 上传失败则卡片显示明确失败文案
- 永远不写"已转附件"除非 file_key 已拿到
"""
from __future__ import annotations

import re
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .client import FeishuClient


def safe_filename(text: str, fallback: str = "hermes_answer") -> str:
    """从文本生成安全文件名"""
    name = re.sub(r"[^\w\u4e00-\u9fff.-]+", "_", text.strip())[:60]
    return name or fallback


class OverflowFileWriter:
    """将超限内容写入本地 Markdown 文件"""

    def __init__(self, spool_dir: str | Path) -> None:
        self.spool_dir = Path(spool_dir)
        self.spool_dir.mkdir(parents=True, exist_ok=True)

    def write_markdown(
        self,
        *,
        job_id: str,
        title: str,
        content: str,
    ) -> Path:
        """写入 Markdown 文件，返回路径"""
        ts = time.strftime("%Y%m%d-%H%M%S")
        filename = f"{ts}_{safe_filename(title)}_{job_id[:8]}.md"
        path = self.spool_dir / filename

        path.write_text(
            f"# {title}\n\n"
            f"> Generated by Hermes · MemoryX\n\n"
            f"{content.strip()}\n",
            encoding="utf-8",
        )

        return path


async def upload_overflow_file(
    client: "FeishuClient",
    *,
    file_path: Path,
    file_name: str,
) -> str | None:
    """上传溢出文件到飞书云盘，返回 file_key"""
    try:
        return await client.upload_file(
            path=str(file_path),
            file_type="stream",
        )
    except Exception:
        return None